import { Category } from '../types/category.types';

export const DEFAULT_CATEGORIES: Omit<Category, 'createdAt' | 'updatedAt'>[] = [
  // ── Expense Categories ──────────────────────────────────────────────────────
  {
    id: 'cat_food',
    name: 'Food & Drinks',
    type: 'expense',
    icon: 'fast-food-outline',
    color: '#F59E0B',
    isSystem: true,
    isArchived: false,
    sortOrder: 0,
  },
  {
    id: 'cat_transport',
    name: 'Transport',
    type: 'expense',
    icon: 'car-outline',
    color: '#3B82F6',
    isSystem: true,
    isArchived: false,
    sortOrder: 1,
  },
  {
    id: 'cat_bills',
    name: 'Bills & Utilities',
    type: 'expense',
    icon: 'receipt-outline',
    color: '#EF4444',
    isSystem: true,
    isArchived: false,
    sortOrder: 2,
  },
  {
    id: 'cat_shopping',
    name: 'Shopping',
    type: 'expense',
    icon: 'bag-outline',
    color: '#EC4899',
    isSystem: true,
    isArchived: false,
    sortOrder: 3,
  },
  {
    id: 'cat_health',
    name: 'Health',
    type: 'expense',
    icon: 'medkit-outline',
    color: '#10B981',
    isSystem: true,
    isArchived: false,
    sortOrder: 4,
  },
  {
    id: 'cat_entertainment',
    name: 'Entertainment',
    type: 'expense',
    icon: 'game-controller-outline',
    color: '#8B5CF6',
    isSystem: true,
    isArchived: false,
    sortOrder: 5,
  },
  {
    id: 'cat_education',
    name: 'Education',
    type: 'expense',
    icon: 'book-outline',
    color: '#06B6D4',
    isSystem: true,
    isArchived: false,
    sortOrder: 6,
  },
  {
    id: 'cat_groceries',
    name: 'Groceries',
    type: 'expense',
    icon: 'basket-outline',
    color: '#84CC16',
    isSystem: true,
    isArchived: false,
    sortOrder: 7,
  },
  {
    id: 'cat_other_expense',
    name: 'Other',
    type: 'expense',
    icon: 'ellipsis-horizontal-circle-outline',
    color: '#6B7280',
    isSystem: true,
    isArchived: false,
    sortOrder: 8,
  },
  // ── Income Categories ───────────────────────────────────────────────────────
  {
    id: 'cat_salary',
    name: 'Salary',
    type: 'income',
    icon: 'briefcase-outline',
    color: '#10B981',
    isSystem: true,
    isArchived: false,
    sortOrder: 0,
  },
  {
    id: 'cat_freelance',
    name: 'Freelance',
    type: 'income',
    icon: 'laptop-outline',
    color: '#3B82F6',
    isSystem: true,
    isArchived: false,
    sortOrder: 1,
  },
  {
    id: 'cat_gifts',
    name: 'Gifts',
    type: 'income',
    icon: 'gift-outline',
    color: '#EC4899',
    isSystem: true,
    isArchived: false,
    sortOrder: 2,
  },
  {
    id: 'cat_other_income',
    name: 'Other Income',
    type: 'income',
    icon: 'wallet-outline',
    color: '#6B7280',
    isSystem: true,
    isArchived: false,
    sortOrder: 3,
  },
];

export const PAYMENT_METHODS = [
  { key: 'cash', label: 'Cash', icon: 'cash-outline' },
  { key: 'card', label: 'Card', icon: 'card-outline' },
  { key: 'upi', label: 'UPI', icon: 'phone-portrait-outline' },
  { key: 'bank_transfer', label: 'Bank Transfer', icon: 'swap-horizontal-outline' },
  { key: 'other', label: 'Other', icon: 'ellipsis-horizontal-outline' },
] as const;

export const STORAGE_KEYS = {
  TRANSACTIONS: '@expense_tracker/transactions',
  CATEGORIES: '@expense_tracker/categories',
  BUDGETS: '@expense_tracker/budgets',
  SETTINGS: '@expense_tracker/settings',
  SCHEMA_VERSION: '@expense_tracker/schema_version',
  ONBOARDING: '@expense_tracker/onboarding_flag',
} as const;

export const CURRENT_SCHEMA_VERSION = 1;
